### ISSUE TITLE
Improvement idea: capability of handling multiple servers

### ISSUE THREAD

**Issue by jdehaan** [algorys/redissue#6]
The configuration file could contain a list of servers with aliases for them. The first server being the default if none is specified (as fallback solution)

For using the new feature

`<redissue id='(server_alias_x)#number_issue' ...`

The server alias being one of the preconfigured url aliases. This will make people hosting several servers in parallel happy!

**Comment by algorys** [comment]
Very good idea.

Thanks.

**Comment by algorys** [comment]
@jdehaan I'm trying to think how to implement this idea.

If handling mulitple server, url of server, alias and API key may be linked...
- [x] Add possibility to have multiple url.
- [x] Get alias from server.
- [x] Associate API with alias of servers.

Not sure the settings menu of Dokuwiki will be easy to manage that. Maybe a config file inside plugin or something like that.

**Comment by selivan** [comment]
>  Not sure the settings menu of Dokuwiki will be easy to manage that

Possible kludge: big textarea(I believe dokuwiki settings menu can do that) whith json or yaml inside:

``` yaml
servers:
  - alias: default
    url: http://example.com/
    api_token: 1234567890
  - alias: second
    url: http://example2.com/
    api_token: 0987654321
```
